name: Python package

on:
  release:
    types: [created]
  push:
    branches: master
    paths-ignore:
      - '.github/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    #- name: Install dependencies
    #  run:
    #    python -m pip install --upgrade pip
    #    pip install -r requirements.txt
    - name: Test with pytest
      env:
        USERNAME: ${{ secrets.username }}
        PASSWORD: ${{ secrets.password }}
      run:
        echo "username > ${USERNAME}"
        python Hello_github.py
